
import Footer from './components/fotter/fotter'
import Header from './components/header/header'
import './globals.css'
import 'remixicon/fonts/remixicon.css'
import "slick-carousel/slick/slick.css"; 
import "slick-carousel/slick/slick-theme.css";



export const metadata = {
  title: 'Addis-Coffe',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body >
      <Header/>
        {children}
        <Footer/>
        </body>
     
    </html>
  )
}
