
import Footer from './components/fotter/fotter'
import Header from './components/header/header'
import './globals.css'




export const metadata = {
  title: 'Addis-Coffe',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body >
      <Header/>
        {children}
      
        <Footer/>
        </body>
     
    </html>
  )
}
